const images = {
  computers: require('./scheme/computers.webp'),
  formationOfNeed: require('./scheme/formationOfNeed.webp'),
  procurementPlan: require('./scheme/procurementPlan.webp'),
  loader: require('./scheme/loader.webp'),
  peopleShakingHands: require('./scheme/peopleShakingHands.webp'),
  conclusionOfContracts: require('./scheme/conclusionOfContracts.webp'),
  folders: require('./normativeBase/folders.webp'),
  foldersTwo: require('./normativeBase/foldersTwo.webp'),
  loaderTwo: require('./normativeBase/loaderTwo.webp'),
  openBook: require('./normativeBase/openBook.webp'),
  peopleAtTheTable: require('./normativeBase/peopleAtTheTable.webp'),
  asez: require('./informationSystems/asez.webp'),
  cloudWithLetter: require('./informationSystems/cloudWithLetter.webp'),
  cloudWithMan: require('./informationSystems/cloudWithMan.webp'),
  computer: require('./informationSystems/computer.webp'),
  computersTwo: require('./informationSystems/computersTwo.webp'),
  computerTwo: require('./informationSystems/computerTwo.webp'),
  listPurple: require('./informationSystems/listPurple.webp'),
  manAtTheComputer: require('./informationSystems/manAtTheComputer.webp'),
  manWithCloud: require('./informationSystems/manWithCloud.webp'),
  server: require('./informationSystems/server.webp'),
  formationOfNeedTwo: require('./listOfParticipants/formationOfNeedTwo.webp'),
  man: require('./listOfParticipants/man.webp'),
  manAtTheComputerTwo: require('./listOfParticipants/manAtTheComputerTwo.webp'),
  threeMan: require('./listOfParticipants/threeMan.webp'),
  manWithTable: require('./workingWithContracts/manWithTable.webp'),
  billboard: require('./planningElements/billboard.webp'),
  box: require('./planningElements/box.webp'),
  foldersThree: require('./planningElements/foldersThree.webp'),
  foldersWithBoxes: require('./planningElements/foldersWithBoxes.webp'),
  loaderThree: require('./planningElements/loaderThree.webp'),
  manAtTheComputerThree: require('./planningElements/manAtTheComputerThree.webp'),
  peopleAtTheTableTwo: require('./planningElements/peopleAtTheTableTwo.webp'),
  peopleWithBoxes: require('./planningElements/peopleWithBoxes.webp'),
  peopleWithBoxesTwo: require('./planningElements/peopleWithBoxesTwo.webp'),
  peopleWithClouds: require('./planningElements/peopleWithClouds.webp'),
  rackWithRedBoxes: require('./planningElements/rackWithRedBoxes.webp'),
  redList: require('./planningElements/redList.webp'),
  arrow: require('./icons/arrow.svg'),
  arrowTwo: require('./icons/arrowTwo.svg'),
  three: require('./icons/three.svg'),
  mainBg: require('./main/main.avif')
}

export default images
